runtime: nodejs16

handlers:
  - url: /(.*\..+)$
    static_files: public/\1
    upload: public/(.*\..+)$

  # site root
  - url: /
    static_files: public/index.html
    upload: public/index.html

  - url: /info
    static_files: public/info/index.html
    upload: public/info/index.html

  - url: .*
    script: index.html
