runtime: nodejs16 # or another supported version

handlers:
  - url: /(.*\..+)$
    static_files: public/\1
    upload: public/(.*\..+)$

  - url: /.*
    static_files: public/index.html
    upload: public/index.html
